// Code generated by protoc-gen-go.
// source: rdirsync.proto
// DO NOT EDIT!

/*
Package rdirsync is a generated protocol buffer package.

It is generated from these files:
	rdirsync.proto

It has these top-level messages:
	FetchRequest
	FileChunk
	ReadDirRequest
	FileInfos
	FileInfo
*/
package rdirsync

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FetchRequest struct {
	Path    string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	BufSize int32  `protobuf:"varint,2,opt,name=bufSize" json:"bufSize,omitempty"`
}

func (m *FetchRequest) Reset()                    { *m = FetchRequest{} }
func (m *FetchRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()               {}
func (*FetchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FileChunk struct {
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (m *FileChunk) Reset()                    { *m = FileChunk{} }
func (m *FileChunk) String() string            { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()               {}
func (*FileChunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadDirRequest struct {
	Path        string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	AtMostCount int32  `protobuf:"varint,2,opt,name=atMostCount" json:"atMostCount,omitempty"`
}

func (m *ReadDirRequest) Reset()                    { *m = ReadDirRequest{} }
func (m *ReadDirRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadDirRequest) ProtoMessage()               {}
func (*ReadDirRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type FileInfos struct {
	Infos []*FileInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
}

func (m *FileInfos) Reset()                    { *m = FileInfos{} }
func (m *FileInfos) String() string            { return proto.CompactTextString(m) }
func (*FileInfos) ProtoMessage()               {}
func (*FileInfos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FileInfos) GetInfos() []*FileInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type FileInfo struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size    int64  `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Mode    int32  `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
	ModTime int64  `protobuf:"varint,4,opt,name=modTime" json:"modTime,omitempty"`
	IsDir   bool   `protobuf:"varint,5,opt,name=isDir" json:"isDir,omitempty"`
}

func (m *FileInfo) Reset()                    { *m = FileInfo{} }
func (m *FileInfo) String() string            { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()               {}
func (*FileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*FetchRequest)(nil), "rdirsync.FetchRequest")
	proto.RegisterType((*FileChunk)(nil), "rdirsync.FileChunk")
	proto.RegisterType((*ReadDirRequest)(nil), "rdirsync.ReadDirRequest")
	proto.RegisterType((*FileInfos)(nil), "rdirsync.FileInfos")
	proto.RegisterType((*FileInfo)(nil), "rdirsync.FileInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for RDirSync service

type RDirSyncClient interface {
	FetchFile(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (RDirSync_FetchFileClient, error)
	ReadDir(ctx context.Context, in *ReadDirRequest, opts ...grpc.CallOption) (RDirSync_ReadDirClient, error)
}

type rDirSyncClient struct {
	cc *grpc.ClientConn
}

func NewRDirSyncClient(cc *grpc.ClientConn) RDirSyncClient {
	return &rDirSyncClient{cc}
}

func (c *rDirSyncClient) FetchFile(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (RDirSync_FetchFileClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RDirSync_serviceDesc.Streams[0], c.cc, "/rdirsync.RDirSync/FetchFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &rDirSyncFetchFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RDirSync_FetchFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type rDirSyncFetchFileClient struct {
	grpc.ClientStream
}

func (x *rDirSyncFetchFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rDirSyncClient) ReadDir(ctx context.Context, in *ReadDirRequest, opts ...grpc.CallOption) (RDirSync_ReadDirClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RDirSync_serviceDesc.Streams[1], c.cc, "/rdirsync.RDirSync/ReadDir", opts...)
	if err != nil {
		return nil, err
	}
	x := &rDirSyncReadDirClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RDirSync_ReadDirClient interface {
	Recv() (*FileInfos, error)
	grpc.ClientStream
}

type rDirSyncReadDirClient struct {
	grpc.ClientStream
}

func (x *rDirSyncReadDirClient) Recv() (*FileInfos, error) {
	m := new(FileInfos)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RDirSync service

type RDirSyncServer interface {
	FetchFile(*FetchRequest, RDirSync_FetchFileServer) error
	ReadDir(*ReadDirRequest, RDirSync_ReadDirServer) error
}

func RegisterRDirSyncServer(s *grpc.Server, srv RDirSyncServer) {
	s.RegisterService(&_RDirSync_serviceDesc, srv)
}

func _RDirSync_FetchFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RDirSyncServer).FetchFile(m, &rDirSyncFetchFileServer{stream})
}

type RDirSync_FetchFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type rDirSyncFetchFileServer struct {
	grpc.ServerStream
}

func (x *rDirSyncFetchFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _RDirSync_ReadDir_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadDirRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RDirSyncServer).ReadDir(m, &rDirSyncReadDirServer{stream})
}

type RDirSync_ReadDirServer interface {
	Send(*FileInfos) error
	grpc.ServerStream
}

type rDirSyncReadDirServer struct {
	grpc.ServerStream
}

func (x *rDirSyncReadDirServer) Send(m *FileInfos) error {
	return x.ServerStream.SendMsg(m)
}

var _RDirSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rdirsync.RDirSync",
	HandlerType: (*RDirSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchFile",
			Handler:       _RDirSync_FetchFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadDir",
			Handler:       _RDirSync_ReadDir_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("rdirsync.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x4e, 0x02, 0x31,
	0x10, 0xb6, 0xc2, 0xca, 0x32, 0x20, 0x87, 0x6a, 0x4c, 0xe3, 0xc5, 0x75, 0x4f, 0x7b, 0xda, 0x18,
	0x8c, 0x37, 0x4e, 0x40, 0x48, 0x3c, 0x98, 0x90, 0xe2, 0x0b, 0xec, 0x4f, 0x71, 0x1b, 0xdc, 0x16,
	0xbb, 0xad, 0x09, 0x3e, 0x80, 0xcf, 0x6d, 0xda, 0xa5, 0x08, 0x1e, 0xbc, 0x7d, 0xdf, 0x64, 0x26,
	0xdf, 0x4f, 0x06, 0x46, 0xaa, 0xe4, 0xaa, 0xd9, 0x89, 0x22, 0xdd, 0x2a, 0xa9, 0x25, 0x0e, 0x3d,
	0x8f, 0x27, 0x30, 0x5c, 0x30, 0x5d, 0x54, 0x94, 0x7d, 0x18, 0xd6, 0x68, 0x8c, 0xa1, 0xbb, 0xcd,
	0x74, 0x45, 0x50, 0x84, 0x92, 0x3e, 0x75, 0x18, 0x13, 0xe8, 0xe5, 0x66, 0xbd, 0xe2, 0x5f, 0x8c,
	0x9c, 0x47, 0x28, 0x09, 0xa8, 0xa7, 0xf1, 0x3d, 0xf4, 0x17, 0xfc, 0x9d, 0xcd, 0x2a, 0x23, 0x36,
	0xf8, 0x1a, 0x82, 0xc2, 0x02, 0x77, 0x3b, 0xa4, 0x2d, 0x89, 0x17, 0x30, 0xa2, 0x2c, 0x2b, 0xe7,
	0x5c, 0xfd, 0x27, 0x11, 0xc1, 0x20, 0xd3, 0x2f, 0xb2, 0xd1, 0x33, 0x69, 0x84, 0xde, 0xcb, 0x1c,
	0x8f, 0xe2, 0xa7, 0x56, 0xea, 0x59, 0xac, 0x65, 0x83, 0x13, 0x08, 0xb8, 0x05, 0x04, 0x45, 0x9d,
	0x64, 0x30, 0xc6, 0xe9, 0x21, 0x9f, 0xdf, 0xa1, 0xed, 0x42, 0xfc, 0x09, 0xa1, 0x1f, 0x59, 0x61,
	0x91, 0xd5, 0xcc, 0x0b, 0x5b, 0x6c, 0x67, 0x8d, 0x0f, 0xd6, 0xa1, 0x0e, 0xdb, 0x59, 0x2d, 0x4b,
	0x46, 0x3a, 0xce, 0x85, 0xc3, 0xb6, 0x83, 0x5a, 0x96, 0xaf, 0xbc, 0x66, 0xa4, 0xeb, 0x56, 0x3d,
	0xb5, 0xb1, 0x79, 0x33, 0xe7, 0x8a, 0x04, 0x11, 0x4a, 0x42, 0xda, 0x92, 0xf1, 0x37, 0x82, 0x90,
	0xce, 0xb9, 0x5a, 0xed, 0x44, 0x81, 0x27, 0xd0, 0x77, 0x25, 0x5b, 0x27, 0xf8, 0xe6, 0xc8, 0xec,
	0x51, 0xf3, 0xb7, 0x57, 0xa7, 0x21, 0x5c, 0xa7, 0xf1, 0xd9, 0x03, 0xc2, 0x13, 0xe8, 0xed, 0x1b,
	0xc4, 0xe4, 0x77, 0xe7, 0xb4, 0xd4, 0xbf, 0xd7, 0xae, 0x26, 0x7b, 0x3d, 0x1d, 0xc3, 0x9d, 0x54,
	0x6f, 0x69, 0xce, 0x75, 0x6e, 0x8a, 0x0d, 0xd3, 0x69, 0x25, 0xb2, 0x4d, 0x56, 0x1b, 0x75, 0x38,
	0x98, 0x5e, 0x7a, 0xa3, 0x4b, 0xfb, 0x1c, 0x4b, 0x94, 0x5f, 0xb8, 0x2f, 0x79, 0xfc, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x59, 0x9f, 0x91, 0xcc, 0x37, 0x02, 0x00, 0x00,
}
